
interface _GlobalComponents {
      'IconHover': typeof import("../components/IconHover.vue")['default']
    'StoreComments': typeof import("../components/StoreComments.vue")['default']
    'AuthConfirmCode': typeof import("../components/auth/ConfirmCode.vue")['default']
    'AuthLoginForgotPassword': typeof import("../components/auth/login/ForgotPassword.vue")['default']
    'AuthLoginForgotPasswordResetPassword': typeof import("../components/auth/login/ForgotPassword/ResetPassword.vue")['default']
    'AuthLoginForgotPasswordSendCode': typeof import("../components/auth/login/ForgotPassword/SendCode.vue")['default']
    'AuthRegisterAccountForm': typeof import("../components/auth/register/AccountForm.vue")['default']
    'AuthRegisterModal': typeof import("../components/auth/register/Modal.vue")['default']
    'AuthRegisterStoreForm': typeof import("../components/auth/register/StoreForm.vue")['default']
    'ContactUsInfo': typeof import("../components/contact-us/Info.vue")['default']
    'ContactUsMessageForm': typeof import("../components/contact-us/MessageForm.vue")['default']
    'FinanceTreatementsSloganCard': typeof import("../components/finance_treatements/SloganCard.vue")['default']
    'FinanceTreatementsSummayCard': typeof import("../components/finance_treatements/SummayCard.vue")['default']
    'GeneralActionModal': typeof import("../components/general/ActionModal.vue")['default']
    'GeneralImagesUploaderMultiple': typeof import("../components/general/ImagesUploaderMultiple.vue")['default']
    'GeneralPageHeading': typeof import("../components/general/PageHeading.vue")['default']
    'GeneralTheButton': typeof import("../components/general/TheButton.vue")['default']
    'GeneralTheCard': typeof import("../components/general/TheCard.vue")['default']
    'GeneralTheDataTable': typeof import("../components/general/TheDataTable.vue")['default']
    'GeneralTheForm': typeof import("../components/general/TheForm.vue")['default']
    'GeneralTheModal': typeof import("../components/general/TheModal.vue")['default']
    'GeneralThePaginator': typeof import("../components/general/ThePaginator.vue")['default']
    'GeneralTheSelectMenu': typeof import("../components/general/TheSelectMenu.vue")['default']
    'GeneralPasswordInput': typeof import("../components/general/passwordInput.vue")['default']
    'HomeBestSellerProducts': typeof import("../components/home/BestSellerProducts.vue")['default']
    'HomeOrdersPercentageCard': typeof import("../components/home/OrdersPercentageCard.vue")['default']
    'HomeProfitsCard': typeof import("../components/home/ProfitsCard.vue")['default']
    'HomeSalesCard': typeof import("../components/home/SalesCard.vue")['default']
    'HomeStatisticsCard': typeof import("../components/home/StatisticsCard.vue")['default']
    'LayoutNavbar': typeof import("../components/layout/Navbar.vue")['default']
    'LayoutPageHeading': typeof import("../components/layout/PageHeading.vue")['default']
    'LayoutSidebar': typeof import("../components/layout/Sidebar.vue")['default']
    'LayoutAuthImageSlogan': typeof import("../components/layout/auth/ImageSlogan.vue")['default']
    'LayoutNavbarLanguages': typeof import("../components/layout/navbar/Languages.vue")['default']
    'LayoutNavbarNotifications': typeof import("../components/layout/navbar/Notifications.vue")['default']
    'OrderDetailsSteps': typeof import("../components/order/DetailsSteps.vue")['default']
    'OrderInfo': typeof import("../components/order/Info.vue")['default']
    'OrderProductsTable': typeof import("../components/order/ProductsTable.vue")['default']
    'ProductItemCard': typeof import("../components/product/ItemCard.vue")['default']
    'ProductAttributesCard': typeof import("../components/product/attributesCard.vue")['default']
    'ProductGroupAttributesForm': typeof import("../components/product/group/AttributesForm.vue")['default']
    'ProductGroupAttributesTable': typeof import("../components/product/group/AttributesTable.vue")['default']
    'ProductGroupDefaultProduct': typeof import("../components/product/group/DefaultProduct.vue")['default']
    'ProductGroupDelete': typeof import("../components/product/group/Delete.vue")['default']
    'ProductGroupEdit': typeof import("../components/product/group/Edit.vue")['default']
    'ProductTableDelete': typeof import("../components/product/table/Delete.vue")['default']
    'ProductTableStatus': typeof import("../components/product/table/Status.vue")['default']
    'SettingsAccountInfo': typeof import("../components/settings/AccountInfo.vue")['default']
    'SettingsCheckPasswordForm': typeof import("../components/settings/CheckPasswordForm.vue")['default']
    'SettingsStoreInfo': typeof import("../components/settings/StoreInfo.vue")['default']
    'SettingsAccountInfoName': typeof import("../components/settings/account-info/Name.vue")['default']
    'SettingsAccountInfoNameForm': typeof import("../components/settings/account-info/NameForm.vue")['default']
    'SettingsAccountInfoNameModal': typeof import("../components/settings/account-info/NameModal.vue")['default']
    'SettingsAccountInfoPassword': typeof import("../components/settings/account-info/Password.vue")['default']
    'SettingsAccountInfoPasswordForm': typeof import("../components/settings/account-info/PasswordForm.vue")['default']
    'SettingsAccountInfoPasswordModal': typeof import("../components/settings/account-info/PasswordModal.vue")['default']
    'SettingsAccountInfoPhone': typeof import("../components/settings/account-info/Phone.vue")['default']
    'SettingsAccountInfoPhoneForm': typeof import("../components/settings/account-info/PhoneForm.vue")['default']
    'SettingsAccountInfoPhoneModal': typeof import("../components/settings/account-info/PhoneModal.vue")['default']
    'SettingsStoreInfoModal': typeof import("../components/settings/store-info/Modal.vue")['default']
    'UserAction': typeof import("../components/user/Action.vue")['default']
    'UserDelete': typeof import("../components/user/Delete.vue")['default']
    'UserDetailsCard': typeof import("../components/user/DetailsCard.vue")['default']
    'UserTable': typeof import("../components/user/Table.vue")['default']
    'UAccordion': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
    'UAlert': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
    'UAvatar': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
    'UAvatarGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
    'UBadge': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
    'UButton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
    'UButtonGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
    'UCarousel': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
    'UChip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
    'UDropdown': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
    'UIcon': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
    'UKbd': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
    'ULink': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
    'UMeter': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
    'UMeterGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
    'UProgress': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
    'UCheckbox': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
    'UForm': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
    'UFormGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
    'UInput': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
    'UInputMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
    'URadio': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
    'URadioGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
    'URange': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
    'USelect': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
    'USelectMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
    'UTextarea': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
    'UToggle': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
    'UTable': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
    'UCard': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
    'UContainer': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
    'UDivider': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
    'USkeleton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
    'UBreadcrumb': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
    'UCommandPalette': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
    'UCommandPaletteGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
    'UHorizontalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
    'UPagination': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
    'UTabs': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
    'UVerticalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
    'UContextMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
    'UModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
    'UModals': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
    'UNotification': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
    'UNotifications': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
    'UPopover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
    'USlideover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
    'USlideovers': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
    'UTooltip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'UModals': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'USlideovers': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
      'LazyIconHover': typeof import("../components/IconHover.vue")['default']
    'LazyStoreComments': typeof import("../components/StoreComments.vue")['default']
    'LazyAuthConfirmCode': typeof import("../components/auth/ConfirmCode.vue")['default']
    'LazyAuthLoginForgotPassword': typeof import("../components/auth/login/ForgotPassword.vue")['default']
    'LazyAuthLoginForgotPasswordResetPassword': typeof import("../components/auth/login/ForgotPassword/ResetPassword.vue")['default']
    'LazyAuthLoginForgotPasswordSendCode': typeof import("../components/auth/login/ForgotPassword/SendCode.vue")['default']
    'LazyAuthRegisterAccountForm': typeof import("../components/auth/register/AccountForm.vue")['default']
    'LazyAuthRegisterModal': typeof import("../components/auth/register/Modal.vue")['default']
    'LazyAuthRegisterStoreForm': typeof import("../components/auth/register/StoreForm.vue")['default']
    'LazyContactUsInfo': typeof import("../components/contact-us/Info.vue")['default']
    'LazyContactUsMessageForm': typeof import("../components/contact-us/MessageForm.vue")['default']
    'LazyFinanceTreatementsSloganCard': typeof import("../components/finance_treatements/SloganCard.vue")['default']
    'LazyFinanceTreatementsSummayCard': typeof import("../components/finance_treatements/SummayCard.vue")['default']
    'LazyGeneralActionModal': typeof import("../components/general/ActionModal.vue")['default']
    'LazyGeneralImagesUploaderMultiple': typeof import("../components/general/ImagesUploaderMultiple.vue")['default']
    'LazyGeneralPageHeading': typeof import("../components/general/PageHeading.vue")['default']
    'LazyGeneralTheButton': typeof import("../components/general/TheButton.vue")['default']
    'LazyGeneralTheCard': typeof import("../components/general/TheCard.vue")['default']
    'LazyGeneralTheDataTable': typeof import("../components/general/TheDataTable.vue")['default']
    'LazyGeneralTheForm': typeof import("../components/general/TheForm.vue")['default']
    'LazyGeneralTheModal': typeof import("../components/general/TheModal.vue")['default']
    'LazyGeneralThePaginator': typeof import("../components/general/ThePaginator.vue")['default']
    'LazyGeneralTheSelectMenu': typeof import("../components/general/TheSelectMenu.vue")['default']
    'LazyGeneralPasswordInput': typeof import("../components/general/passwordInput.vue")['default']
    'LazyHomeBestSellerProducts': typeof import("../components/home/BestSellerProducts.vue")['default']
    'LazyHomeOrdersPercentageCard': typeof import("../components/home/OrdersPercentageCard.vue")['default']
    'LazyHomeProfitsCard': typeof import("../components/home/ProfitsCard.vue")['default']
    'LazyHomeSalesCard': typeof import("../components/home/SalesCard.vue")['default']
    'LazyHomeStatisticsCard': typeof import("../components/home/StatisticsCard.vue")['default']
    'LazyLayoutNavbar': typeof import("../components/layout/Navbar.vue")['default']
    'LazyLayoutPageHeading': typeof import("../components/layout/PageHeading.vue")['default']
    'LazyLayoutSidebar': typeof import("../components/layout/Sidebar.vue")['default']
    'LazyLayoutAuthImageSlogan': typeof import("../components/layout/auth/ImageSlogan.vue")['default']
    'LazyLayoutNavbarLanguages': typeof import("../components/layout/navbar/Languages.vue")['default']
    'LazyLayoutNavbarNotifications': typeof import("../components/layout/navbar/Notifications.vue")['default']
    'LazyOrderDetailsSteps': typeof import("../components/order/DetailsSteps.vue")['default']
    'LazyOrderInfo': typeof import("../components/order/Info.vue")['default']
    'LazyOrderProductsTable': typeof import("../components/order/ProductsTable.vue")['default']
    'LazyProductItemCard': typeof import("../components/product/ItemCard.vue")['default']
    'LazyProductAttributesCard': typeof import("../components/product/attributesCard.vue")['default']
    'LazyProductGroupAttributesForm': typeof import("../components/product/group/AttributesForm.vue")['default']
    'LazyProductGroupAttributesTable': typeof import("../components/product/group/AttributesTable.vue")['default']
    'LazyProductGroupDefaultProduct': typeof import("../components/product/group/DefaultProduct.vue")['default']
    'LazyProductGroupDelete': typeof import("../components/product/group/Delete.vue")['default']
    'LazyProductGroupEdit': typeof import("../components/product/group/Edit.vue")['default']
    'LazyProductTableDelete': typeof import("../components/product/table/Delete.vue")['default']
    'LazyProductTableStatus': typeof import("../components/product/table/Status.vue")['default']
    'LazySettingsAccountInfo': typeof import("../components/settings/AccountInfo.vue")['default']
    'LazySettingsCheckPasswordForm': typeof import("../components/settings/CheckPasswordForm.vue")['default']
    'LazySettingsStoreInfo': typeof import("../components/settings/StoreInfo.vue")['default']
    'LazySettingsAccountInfoName': typeof import("../components/settings/account-info/Name.vue")['default']
    'LazySettingsAccountInfoNameForm': typeof import("../components/settings/account-info/NameForm.vue")['default']
    'LazySettingsAccountInfoNameModal': typeof import("../components/settings/account-info/NameModal.vue")['default']
    'LazySettingsAccountInfoPassword': typeof import("../components/settings/account-info/Password.vue")['default']
    'LazySettingsAccountInfoPasswordForm': typeof import("../components/settings/account-info/PasswordForm.vue")['default']
    'LazySettingsAccountInfoPasswordModal': typeof import("../components/settings/account-info/PasswordModal.vue")['default']
    'LazySettingsAccountInfoPhone': typeof import("../components/settings/account-info/Phone.vue")['default']
    'LazySettingsAccountInfoPhoneForm': typeof import("../components/settings/account-info/PhoneForm.vue")['default']
    'LazySettingsAccountInfoPhoneModal': typeof import("../components/settings/account-info/PhoneModal.vue")['default']
    'LazySettingsStoreInfoModal': typeof import("../components/settings/store-info/Modal.vue")['default']
    'LazyUserAction': typeof import("../components/user/Action.vue")['default']
    'LazyUserDelete': typeof import("../components/user/Delete.vue")['default']
    'LazyUserDetailsCard': typeof import("../components/user/DetailsCard.vue")['default']
    'LazyUserTable': typeof import("../components/user/Table.vue")['default']
    'LazyUAccordion': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
    'LazyUAlert': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
    'LazyUAvatar': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
    'LazyUAvatarGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
    'LazyUBadge': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
    'LazyUButton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
    'LazyUButtonGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
    'LazyUCarousel': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
    'LazyUChip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
    'LazyUDropdown': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
    'LazyUIcon': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
    'LazyUKbd': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
    'LazyULink': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
    'LazyUMeter': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
    'LazyUMeterGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
    'LazyUProgress': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
    'LazyUCheckbox': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
    'LazyUForm': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
    'LazyUFormGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
    'LazyUInput': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
    'LazyUInputMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
    'LazyURadio': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
    'LazyURadioGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
    'LazyURange': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
    'LazyUSelect': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
    'LazyUSelectMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
    'LazyUTextarea': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
    'LazyUToggle': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
    'LazyUTable': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
    'LazyUCard': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
    'LazyUContainer': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
    'LazyUDivider': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
    'LazyUSkeleton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
    'LazyUBreadcrumb': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
    'LazyUCommandPalette': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
    'LazyUCommandPaletteGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
    'LazyUHorizontalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
    'LazyUPagination': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
    'LazyUTabs': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
    'LazyUVerticalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
    'LazyUContextMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
    'LazyUModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
    'LazyUModals': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
    'LazyUNotification': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
    'LazyUNotifications': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
    'LazyUPopover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
    'LazyUSlideover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
    'LazyUSlideovers': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
    'LazyUTooltip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyUModals': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyUSlideovers': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const IconHover: typeof import("../components/IconHover.vue")['default']
export const StoreComments: typeof import("../components/StoreComments.vue")['default']
export const AuthConfirmCode: typeof import("../components/auth/ConfirmCode.vue")['default']
export const AuthLoginForgotPassword: typeof import("../components/auth/login/ForgotPassword.vue")['default']
export const AuthLoginForgotPasswordResetPassword: typeof import("../components/auth/login/ForgotPassword/ResetPassword.vue")['default']
export const AuthLoginForgotPasswordSendCode: typeof import("../components/auth/login/ForgotPassword/SendCode.vue")['default']
export const AuthRegisterAccountForm: typeof import("../components/auth/register/AccountForm.vue")['default']
export const AuthRegisterModal: typeof import("../components/auth/register/Modal.vue")['default']
export const AuthRegisterStoreForm: typeof import("../components/auth/register/StoreForm.vue")['default']
export const ContactUsInfo: typeof import("../components/contact-us/Info.vue")['default']
export const ContactUsMessageForm: typeof import("../components/contact-us/MessageForm.vue")['default']
export const FinanceTreatementsSloganCard: typeof import("../components/finance_treatements/SloganCard.vue")['default']
export const FinanceTreatementsSummayCard: typeof import("../components/finance_treatements/SummayCard.vue")['default']
export const GeneralActionModal: typeof import("../components/general/ActionModal.vue")['default']
export const GeneralImagesUploaderMultiple: typeof import("../components/general/ImagesUploaderMultiple.vue")['default']
export const GeneralPageHeading: typeof import("../components/general/PageHeading.vue")['default']
export const GeneralTheButton: typeof import("../components/general/TheButton.vue")['default']
export const GeneralTheCard: typeof import("../components/general/TheCard.vue")['default']
export const GeneralTheDataTable: typeof import("../components/general/TheDataTable.vue")['default']
export const GeneralTheForm: typeof import("../components/general/TheForm.vue")['default']
export const GeneralTheModal: typeof import("../components/general/TheModal.vue")['default']
export const GeneralThePaginator: typeof import("../components/general/ThePaginator.vue")['default']
export const GeneralTheSelectMenu: typeof import("../components/general/TheSelectMenu.vue")['default']
export const GeneralPasswordInput: typeof import("../components/general/passwordInput.vue")['default']
export const HomeBestSellerProducts: typeof import("../components/home/BestSellerProducts.vue")['default']
export const HomeOrdersPercentageCard: typeof import("../components/home/OrdersPercentageCard.vue")['default']
export const HomeProfitsCard: typeof import("../components/home/ProfitsCard.vue")['default']
export const HomeSalesCard: typeof import("../components/home/SalesCard.vue")['default']
export const HomeStatisticsCard: typeof import("../components/home/StatisticsCard.vue")['default']
export const LayoutNavbar: typeof import("../components/layout/Navbar.vue")['default']
export const LayoutPageHeading: typeof import("../components/layout/PageHeading.vue")['default']
export const LayoutSidebar: typeof import("../components/layout/Sidebar.vue")['default']
export const LayoutAuthImageSlogan: typeof import("../components/layout/auth/ImageSlogan.vue")['default']
export const LayoutNavbarLanguages: typeof import("../components/layout/navbar/Languages.vue")['default']
export const LayoutNavbarNotifications: typeof import("../components/layout/navbar/Notifications.vue")['default']
export const OrderDetailsSteps: typeof import("../components/order/DetailsSteps.vue")['default']
export const OrderInfo: typeof import("../components/order/Info.vue")['default']
export const OrderProductsTable: typeof import("../components/order/ProductsTable.vue")['default']
export const ProductItemCard: typeof import("../components/product/ItemCard.vue")['default']
export const ProductAttributesCard: typeof import("../components/product/attributesCard.vue")['default']
export const ProductGroupAttributesForm: typeof import("../components/product/group/AttributesForm.vue")['default']
export const ProductGroupAttributesTable: typeof import("../components/product/group/AttributesTable.vue")['default']
export const ProductGroupDefaultProduct: typeof import("../components/product/group/DefaultProduct.vue")['default']
export const ProductGroupDelete: typeof import("../components/product/group/Delete.vue")['default']
export const ProductGroupEdit: typeof import("../components/product/group/Edit.vue")['default']
export const ProductTableDelete: typeof import("../components/product/table/Delete.vue")['default']
export const ProductTableStatus: typeof import("../components/product/table/Status.vue")['default']
export const SettingsAccountInfo: typeof import("../components/settings/AccountInfo.vue")['default']
export const SettingsCheckPasswordForm: typeof import("../components/settings/CheckPasswordForm.vue")['default']
export const SettingsStoreInfo: typeof import("../components/settings/StoreInfo.vue")['default']
export const SettingsAccountInfoName: typeof import("../components/settings/account-info/Name.vue")['default']
export const SettingsAccountInfoNameForm: typeof import("../components/settings/account-info/NameForm.vue")['default']
export const SettingsAccountInfoNameModal: typeof import("../components/settings/account-info/NameModal.vue")['default']
export const SettingsAccountInfoPassword: typeof import("../components/settings/account-info/Password.vue")['default']
export const SettingsAccountInfoPasswordForm: typeof import("../components/settings/account-info/PasswordForm.vue")['default']
export const SettingsAccountInfoPasswordModal: typeof import("../components/settings/account-info/PasswordModal.vue")['default']
export const SettingsAccountInfoPhone: typeof import("../components/settings/account-info/Phone.vue")['default']
export const SettingsAccountInfoPhoneForm: typeof import("../components/settings/account-info/PhoneForm.vue")['default']
export const SettingsAccountInfoPhoneModal: typeof import("../components/settings/account-info/PhoneModal.vue")['default']
export const SettingsStoreInfoModal: typeof import("../components/settings/store-info/Modal.vue")['default']
export const UserAction: typeof import("../components/user/Action.vue")['default']
export const UserDelete: typeof import("../components/user/Delete.vue")['default']
export const UserDetailsCard: typeof import("../components/user/DetailsCard.vue")['default']
export const UserTable: typeof import("../components/user/Table.vue")['default']
export const UAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
export const UAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
export const UAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
export const UAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
export const UBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
export const UButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
export const UButtonGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
export const UCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
export const UChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
export const UDropdown: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
export const UIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
export const UKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
export const ULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
export const UMeter: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
export const UMeterGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
export const UProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
export const UCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
export const UForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
export const UFormGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
export const UInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
export const UInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
export const URadio: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
export const URadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
export const URange: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
export const USelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
export const USelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
export const UTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
export const UToggle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
export const UTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
export const UCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
export const UContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
export const UDivider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
export const USkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
export const UBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
export const UCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
export const UCommandPaletteGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
export const UHorizontalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
export const UPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
export const UTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
export const UVerticalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
export const UContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
export const UModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
export const UModals: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
export const UNotification: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
export const UNotifications: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
export const UPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
export const USlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
export const USlideovers: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
export const UTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const UModals: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const USlideovers: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyIconHover: typeof import("../components/IconHover.vue")['default']
export const LazyStoreComments: typeof import("../components/StoreComments.vue")['default']
export const LazyAuthConfirmCode: typeof import("../components/auth/ConfirmCode.vue")['default']
export const LazyAuthLoginForgotPassword: typeof import("../components/auth/login/ForgotPassword.vue")['default']
export const LazyAuthLoginForgotPasswordResetPassword: typeof import("../components/auth/login/ForgotPassword/ResetPassword.vue")['default']
export const LazyAuthLoginForgotPasswordSendCode: typeof import("../components/auth/login/ForgotPassword/SendCode.vue")['default']
export const LazyAuthRegisterAccountForm: typeof import("../components/auth/register/AccountForm.vue")['default']
export const LazyAuthRegisterModal: typeof import("../components/auth/register/Modal.vue")['default']
export const LazyAuthRegisterStoreForm: typeof import("../components/auth/register/StoreForm.vue")['default']
export const LazyContactUsInfo: typeof import("../components/contact-us/Info.vue")['default']
export const LazyContactUsMessageForm: typeof import("../components/contact-us/MessageForm.vue")['default']
export const LazyFinanceTreatementsSloganCard: typeof import("../components/finance_treatements/SloganCard.vue")['default']
export const LazyFinanceTreatementsSummayCard: typeof import("../components/finance_treatements/SummayCard.vue")['default']
export const LazyGeneralActionModal: typeof import("../components/general/ActionModal.vue")['default']
export const LazyGeneralImagesUploaderMultiple: typeof import("../components/general/ImagesUploaderMultiple.vue")['default']
export const LazyGeneralPageHeading: typeof import("../components/general/PageHeading.vue")['default']
export const LazyGeneralTheButton: typeof import("../components/general/TheButton.vue")['default']
export const LazyGeneralTheCard: typeof import("../components/general/TheCard.vue")['default']
export const LazyGeneralTheDataTable: typeof import("../components/general/TheDataTable.vue")['default']
export const LazyGeneralTheForm: typeof import("../components/general/TheForm.vue")['default']
export const LazyGeneralTheModal: typeof import("../components/general/TheModal.vue")['default']
export const LazyGeneralThePaginator: typeof import("../components/general/ThePaginator.vue")['default']
export const LazyGeneralTheSelectMenu: typeof import("../components/general/TheSelectMenu.vue")['default']
export const LazyGeneralPasswordInput: typeof import("../components/general/passwordInput.vue")['default']
export const LazyHomeBestSellerProducts: typeof import("../components/home/BestSellerProducts.vue")['default']
export const LazyHomeOrdersPercentageCard: typeof import("../components/home/OrdersPercentageCard.vue")['default']
export const LazyHomeProfitsCard: typeof import("../components/home/ProfitsCard.vue")['default']
export const LazyHomeSalesCard: typeof import("../components/home/SalesCard.vue")['default']
export const LazyHomeStatisticsCard: typeof import("../components/home/StatisticsCard.vue")['default']
export const LazyLayoutNavbar: typeof import("../components/layout/Navbar.vue")['default']
export const LazyLayoutPageHeading: typeof import("../components/layout/PageHeading.vue")['default']
export const LazyLayoutSidebar: typeof import("../components/layout/Sidebar.vue")['default']
export const LazyLayoutAuthImageSlogan: typeof import("../components/layout/auth/ImageSlogan.vue")['default']
export const LazyLayoutNavbarLanguages: typeof import("../components/layout/navbar/Languages.vue")['default']
export const LazyLayoutNavbarNotifications: typeof import("../components/layout/navbar/Notifications.vue")['default']
export const LazyOrderDetailsSteps: typeof import("../components/order/DetailsSteps.vue")['default']
export const LazyOrderInfo: typeof import("../components/order/Info.vue")['default']
export const LazyOrderProductsTable: typeof import("../components/order/ProductsTable.vue")['default']
export const LazyProductItemCard: typeof import("../components/product/ItemCard.vue")['default']
export const LazyProductAttributesCard: typeof import("../components/product/attributesCard.vue")['default']
export const LazyProductGroupAttributesForm: typeof import("../components/product/group/AttributesForm.vue")['default']
export const LazyProductGroupAttributesTable: typeof import("../components/product/group/AttributesTable.vue")['default']
export const LazyProductGroupDefaultProduct: typeof import("../components/product/group/DefaultProduct.vue")['default']
export const LazyProductGroupDelete: typeof import("../components/product/group/Delete.vue")['default']
export const LazyProductGroupEdit: typeof import("../components/product/group/Edit.vue")['default']
export const LazyProductTableDelete: typeof import("../components/product/table/Delete.vue")['default']
export const LazyProductTableStatus: typeof import("../components/product/table/Status.vue")['default']
export const LazySettingsAccountInfo: typeof import("../components/settings/AccountInfo.vue")['default']
export const LazySettingsCheckPasswordForm: typeof import("../components/settings/CheckPasswordForm.vue")['default']
export const LazySettingsStoreInfo: typeof import("../components/settings/StoreInfo.vue")['default']
export const LazySettingsAccountInfoName: typeof import("../components/settings/account-info/Name.vue")['default']
export const LazySettingsAccountInfoNameForm: typeof import("../components/settings/account-info/NameForm.vue")['default']
export const LazySettingsAccountInfoNameModal: typeof import("../components/settings/account-info/NameModal.vue")['default']
export const LazySettingsAccountInfoPassword: typeof import("../components/settings/account-info/Password.vue")['default']
export const LazySettingsAccountInfoPasswordForm: typeof import("../components/settings/account-info/PasswordForm.vue")['default']
export const LazySettingsAccountInfoPasswordModal: typeof import("../components/settings/account-info/PasswordModal.vue")['default']
export const LazySettingsAccountInfoPhone: typeof import("../components/settings/account-info/Phone.vue")['default']
export const LazySettingsAccountInfoPhoneForm: typeof import("../components/settings/account-info/PhoneForm.vue")['default']
export const LazySettingsAccountInfoPhoneModal: typeof import("../components/settings/account-info/PhoneModal.vue")['default']
export const LazySettingsStoreInfoModal: typeof import("../components/settings/store-info/Modal.vue")['default']
export const LazyUserAction: typeof import("../components/user/Action.vue")['default']
export const LazyUserDelete: typeof import("../components/user/Delete.vue")['default']
export const LazyUserDetailsCard: typeof import("../components/user/DetailsCard.vue")['default']
export const LazyUserTable: typeof import("../components/user/Table.vue")['default']
export const LazyUAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
export const LazyUAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
export const LazyUAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
export const LazyUAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
export const LazyUBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
export const LazyUButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
export const LazyUButtonGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
export const LazyUCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
export const LazyUChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
export const LazyUDropdown: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
export const LazyUIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
export const LazyUKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
export const LazyULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
export const LazyUMeter: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
export const LazyUMeterGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
export const LazyUProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
export const LazyUCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
export const LazyUForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
export const LazyUFormGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
export const LazyUInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
export const LazyUInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
export const LazyURadio: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
export const LazyURadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
export const LazyURange: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
export const LazyUSelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
export const LazyUSelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
export const LazyUTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
export const LazyUToggle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
export const LazyUTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
export const LazyUCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
export const LazyUContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
export const LazyUDivider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
export const LazyUSkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
export const LazyUBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
export const LazyUCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
export const LazyUCommandPaletteGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
export const LazyUHorizontalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
export const LazyUPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
export const LazyUTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
export const LazyUVerticalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
export const LazyUContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
export const LazyUModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
export const LazyUModals: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
export const LazyUNotification: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
export const LazyUNotifications: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
export const LazyUPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
export const LazyUSlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
export const LazyUSlideovers: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
export const LazyUTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyUModals: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyUSlideovers: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']

export const componentNames: string[]
